name: Deployment pipeline

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  PORT: ${{ secrets.PORT }}
  SECRET: ${{ secrets.SECRET }}

on:
 push:
  branches:
   - main
  pull_request:
   branches: [main]
   types: [opened, synchronize]

jobs:
 deployment_pipeline:
  runs-on: ubuntu-20.04
  steps:
   - uses: actions/checkout@v4

   - uses: actions/setup-node@v4
     with:
      node-version: "20"

   - name: Install frontend dependencies
     working-directory: ./frontend
     run: npm install

   - name: Lint frontend
     working-directory: ./frontend
     run: npm run eslint

   - name: Build frontend
     working-directory: ./frontend
     run: npm run build

   - name: Install backend dependencies
     working-directory: ./backend
     run: npm install

   - name: Start backend
     working-directory: ./backend
     run: npm run start:test &

   - name: Run e2e tests
     uses: cypress-io/github-action@v5
     with:
      env:
        PORT: 3001
      command: npm run test:e2e
      start: npm run start
      wait-on: http://localhost:3001
      working-directory: ./frontend

 tag_release:
  needs: [deployment_pipeline]
  runs-on: ubuntu-20.04
  steps:
   - uses: actions/checkout@v4

   - name: Bump version and push tag
     if: ${{ github.event_name == 'push' }}
     uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEFAULT_BUMP: patch
      RELEASE_BRANCHES: master